export 
    const dataList = [
      // breakfast
        {
          key: "Nasi Lemak (Boon Lay Power Nasi Lemak)", 
          title:"Nasi Lemak (Boon Lay Power Nasi Lemak)",
          image: require('../assets/WestFood/nasilemak.jpg'),
          text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled',
          video: 'KTK2lCyg0-k',
          rating: 4,
          status: 'Halal',
          place: 'Boon Lay',
          page: 'West',
          subpage: 'Boon Lay Place Market and Food Village',
          subpageimg: require('../assets/WestHawker/BLM.jpg'),
          subpageadd: '221A Boon Lay Pl, Singapore 641221',
          subpagetime: '24 hours',
          subpagephone:62255632,
          subpagelat: 1.3467516321919029,
          subpagelong: 103.71298136931848,
          subpagemrt: 'Boon Lay',
          subpagebus: '180, 187, 240, 30, 99',
          subpageplace: 'Boon Lay',
          category: 'breakfast'
        }, 
        {
          key: 'Fried Kway Teow Mee (Ghee Huat)', 
          title:"Fried Kway Teow Mee (Ghee Huat)",
          image: require('../assets/WestFood/teow.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          place:'Boon Lay',
          subpage: 'Boon Lay Place Market and Food Village',
          subpageimg: require('../assets/WestHawker/BLM.jpg'),
          subpageadd: '221A Boon Lay Pl, Singapore 641221',
          subpagetime: '24 hours',
          subpagephone:62255632,
          subpagelat: 1.3467516321919029,
          subpagelong: 103.71298136931848,
          subpagemrt: 'Boon Lay',
          subpagebus: '180, 187, 240, 30, 99',
          subpageplace: 'Boon Lay',
          category: 'breakfast'
        },   
        {
          key: 'Hokkien Prawn Mee (Ho Huat Fried Hokkien Prawn Mee)',
          title:"Hokkien Prawn Mee (Ho Huat Fried Hokkien Prawn Mee)",
          image: require('../assets/WestFood/hmee.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          category: 'breakfast',
          place: 'Boon Lay',
          subpage: 'Boon Lay Place Market and Food Village',
          subpageimg: require('../assets/WestHawker/BLM.jpg'),
          subpageadd: '221A Boon Lay Pl, Singapore 641221',
          subpagetime: '24 hours',
          subpagephone:62255632,
          subpagelat: 1.3467516321919029,
          subpagelong: 103.71298136931848,
          subpagemrt: 'Boon Lay',
          subpagebus: '180, 187, 240, 30, 99',
          subpageplace: 'Boon Lay',
          category: 'breakfast'
        },
        {
          key: 'Ngoh Hiang (Xin Sheng Gor Hiong Prawn Cracker)', 
          title:"Ngoh Hiang (Xin Sheng Gor Hiong Prawn Cracker)",
          image: require('../assets/WestFood/ngoh.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          category: 'breakfast',
          place: 'Boon Lay',
          subpage: 'Boon Lay Place Market and Food Village',
          subpageimg: require('../assets/WestHawker/BLM.jpg'),
          subpageadd: '221A Boon Lay Pl, Singapore 641221',
          subpagetime: '24 hours',
          subpagephone:62255632,
          subpagelat: 1.3467516321919029,
          subpagelong: 103.71298136931848,
          subpagemrt: 'Boon Lay',
          subpagebus: '180, 187, 240, 30, 99',
          subpageplace: 'Boon Lay',
          category: 'breakfast'
        }, 
        {
          key: 'Fish Porridge (Lin Ji Yu Tang Yu Zhou 林記鱼汤鱼粥', 
          title:"Fish Porridge (Lin Ji Yu Tang Yu Zhou 林記鱼汤鱼粥",
          image: require('../assets/WestFood/porriage.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          category: 'breakfast',
          subpage: 'Boon Lay Place Market and Food Village',
          subpageimg: require('../assets/WestHawker/BLM.jpg'),
          subpageadd: '221A Boon Lay Pl, Singapore 641221',
          subpagetime: '24 hours',
          subpagephone:62255632,
          subpagelat: 1.3467516321919029,
          subpagelong: 103.71298136931848,
          subpagemrt: 'Boon Lay',
          subpagebus: '180, 187, 240, 30, 99',
          subpageplace: 'Boon Lay',
          category: 'breakfast'
        },
        {
          key: 'Black Carrot Cake (Boon Lay Fried Carrot Cake & Kway Teow Mee)', 
          title:"Black Carrot Cake (Boon Lay Fried Carrot Cake & Kway Teow Mee)",
          image: require('../assets/WestFood/cake.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          category: 'breakfast',
          subpage: 'Boon Lay Place Market and Food Village',
          subpageimg: require('../assets/WestHawker/BLM.jpg'),
          subpageadd: '221A Boon Lay Pl, Singapore 641221',
          subpagetime: '24 hours',
          subpagephone:62255632,
          subpagelat: 1.3467516321919029,
          subpagelong: 103.71298136931848,
          subpagemrt: 'Boon Lay',
          subpagebus: '180, 187, 240, 30, 99',
          subpageplace: 'Boon Lay',
          category: 'breakfast'
        },
        {
          key: 'Boneless Duck Noodles (Heng Huat)', 
          title:"Boneless Duck Noodles (Heng Huat)",
          image: require('../assets/WestFood/duck.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          category: 'breakfast',
          subpage: 'Boon Lay Place Market and Food Village',
          subpageimg: require('../assets/WestHawker/BLM.jpg'),
          subpageadd: '221A Boon Lay Pl, Singapore 641221',
          subpagetime: '24 hours',
          subpagephone:62255632,
          subpagelat: 1.3467516321919029,
          subpagelong: 103.71298136931848,
          subpagemrt: 'Boon Lay',
          subpagebus: '180, 187, 240, 30, 99',
          subpageplace: 'Boon Lay',
          category: 'breakfast'
        },
        {
          key: 'Ming Kee Porriage', 
          title:'Ming Kee Porriage', 
          image: require('../assets/WestFood/congee.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          category: 'breakfast',
          subpage: 'West Coast Market Square',
          subpageimg: require('../assets/WestHawker/726ClementiWS2.png'),
          subpageadd: '726 Clementi West Street 2, Singapore 120726',
          subpagephone:62255632,
          subpagelat: 1.305339125054957,
          subpagelong: 103.76449489643741,
          subpagemrt: 'Clementi',
          subpagebus: '143, 201, 30, 97',
          subpageplace: 'West Coast',
          category: 'breakfast',
        },
        {
          key: 'Mee Siam (Hani Food Stall)', 
          title:'Mee Siam (Hani Food Stall)', 
          image: require('../assets/WestFood/mani.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          category: 'breakfast',
          subpage: 'West Coast Market Square',
          subpageimg: require('../assets/WestHawker/726ClementiWS2.png'),
          subpageadd: '726 Clementi West Street 2, Singapore 120726',
          subpagephone:62255632,
          subpagelat: 1.305339125054957,
          subpagelong: 103.76449489643741,
          subpagemrt: 'Clementi',
          subpagebus: '143, 201, 30, 97',
          subpageplace: 'West Coast',
          category: 'breakfast',
        },
        {
          key: 'Mei Feng Roasted Chicken Rice', 
          title:'Mei Feng Roasted Chicken Rice', 
          image: require('../assets/WestFood/char.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          category: 'breakfast',
          subpage: 'West Coast Market Square',
          subpageimg: require('../assets/WestHawker/726ClementiWS2.png'),
          subpageadd: '726 Clementi West Street 2, Singapore 120726',
          subpagephone:62255632,
          subpagelat: 1.305339125054957,
          subpagelong: 103.76449489643741,
          subpagemrt: 'Clementi',
          subpagebus: '143, 201, 30, 97',
          subpageplace: 'West Coast',
          category: 'breakfast',
          place: 'West Coast'
        }
          ];
