export 
    const lunchData = [

        // Lunch/Dinner
        {
          key: 'Satay (Boon Lay Satay)', 
          title:"Satay (Boon Lay Satay)",
          image: require('../assets/WestFood/satay.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          place: 'Boon Lay',
          subpage: 'Boon Lay Place Market and Food Village',
          subpageimg: require('../assets/WestHawker/BLM.jpg'),
          subpageadd: '221A Boon Lay Pl, Singapore 641221',
          subpagetime: '24 hours',
          subpagephone:62255632,
          subpagelat: 1.3467516321919029,
          subpagelong: 103.71298136931848,
          subpagemrt: 'Boon Lay',
          subpagebus: '180, 187, 240, 30, 99',
          subpageplace: 'Boon Lay',
          category: 'breakfast'
          
        }, 
        {
            key: 'Chicken Wing (Chong Pang Huat)',
            title:"Chicken Wing (Chong Pang Huat)",
            image: require('../assets/WestFood/chickw.jpg'),
            text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
            rating: 3,
            place: 'Boon Lay',
            subpage: 'Boon Lay Place Market and Food Village',
            subpageimg: require('../assets/WestHawker/BLM.jpg'),
            subpageadd: '221A Boon Lay Pl, Singapore 641221',
            subpagetime: '24 hours',
            subpagephone:62255632,
            subpagelat: 1.3467516321919029,
            subpagelong: 103.71298136931848,
            subpagemrt: 'Boon Lay',
            subpagebus: '180, 187, 240, 30, 99',
            subpageplace: 'Boon Lay',
            category: 'breakfast'
            
          },
        {
          key: 'Sambal Stingray (Lian Yi BBQ Seafood)', 
          title:"Sambal Stingray (Lian Yi BBQ Seafood)",
          image: require('../assets/WestFood/ray.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          place: 'Boon Lay',
          subpage: 'Boon Lay Place Market and Food Village',
          subpageimg: require('../assets/WestHawker/BLM.jpg'),
          subpageadd: '221A Boon Lay Pl, Singapore 641221',
          subpagetime: '24 hours',
          subpagephone:62255632,
          subpagelat: 1.3467516321919029,
          subpagelong: 103.71298136931848,
          subpagemrt: 'Boon Lay',
          subpagebus: '180, 187, 240, 30, 99',
          subpageplace: 'Boon Lay',
          category: 'breakfast'
          
        },
        {
            key: 'Nasi Lemak (Boon Lay Power Nasi Lemak)', 
            title:"Nasi Lemak (Boon Lay Power Nasi Lemak)",
            image: require('../assets/WestFood/nasilemak.jpg'),
            text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled',
            video: 'KTK2lCyg0-k',
            rating: 4,
            status: 'Halal',
            place: 'Boon Lay',
            page: 'West',
            subpage: 'Boon Lay Place Market and Food Village',
            subpageimg: require('../assets/WestHawker/BLM.jpg'),
            subpageadd: '221A Boon Lay Pl, Singapore 641221',
            subpagetime: '24 hours',
            subpagephone:62255632,
            subpagelat: 1.3467516321919029,
            subpagelong: 103.71298136931848,
            subpagemrt: 'Boon Lay',
            subpagebus: '180, 187, 240, 30, 99',
            subpageplace: 'Boon Lay',
            category: 'breakfast'
          }, 
          {
            key: 'Fried Kway Teow Mee (Ghee Huat)', 
            title:"Fried Kway Teow Mee (Ghee Huat)",
            image: require('../assets/WestFood/teow.jpg'),
            text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
            rating: 3,
            place:'Boon Lay',
            subpage: 'Boon Lay Place Market and Food Village',
            subpageimg: require('../assets/WestHawker/BLM.jpg'),
            subpageadd: '221A Boon Lay Pl, Singapore 641221',
            subpagetime: '24 hours',
            subpagephone:62255632,
            subpagelat: 1.3467516321919029,
            subpagelong: 103.71298136931848,
            subpagemrt: 'Boon Lay',
            subpagebus: '180, 187, 240, 30, 99',
            subpageplace: 'Boon Lay',
            category: 'breakfast'
          },   
          {
            key: 'Hokkien Prawn Mee (Ho Huat Fried Hokkien Prawn Mee)',
            title:"Hokkien Prawn Mee (Ho Huat Fried Hokkien Prawn Mee)",
            image: require('../assets/WestFood/hmee.jpg'),
            text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
            rating: 3,
            status: 'All',
            category: 'breakfast',
            place: 'Boon Lay',
            subpage: 'Boon Lay Place Market and Food Village',
            subpageimg: require('../assets/WestHawker/BLM.jpg'),
            subpageadd: '221A Boon Lay Pl, Singapore 641221',
            subpagetime: '24 hours',
            subpagephone:62255632,
            subpagelat: 1.3467516321919029,
            subpagelong: 103.71298136931848,
            subpagemrt: 'Boon Lay',
            subpagebus: '180, 187, 240, 30, 99',
            subpageplace: 'Boon Lay',
            category: 'breakfast'
          },
          {
            key: 'Ngoh Hiang', 
            title:"Ngoh Hiang (Xin Sheng Gor Hiong Prawn Cracker)",
            image: require('../assets/WestFood/ngoh.jpg'),
            text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
            rating: 3,
            status: 'All',
            category: 'breakfast',
            place: 'Boon Lay',
            subpage: 'Boon Lay Place Market and Food Village',
            subpageimg: require('../assets/WestHawker/BLM.jpg'),
            subpageadd: '221A Boon Lay Pl, Singapore 641221',
            subpagetime: '24 hours',
            subpagephone:62255632,
            subpagelat: 1.3467516321919029,
            subpagelong: 103.71298136931848,
            subpagemrt: 'Boon Lay',
            subpagebus: '180, 187, 240, 30, 99',
            subpageplace: 'Boon Lay',
            category: 'breakfast'
          }, 
          {
            key: 'Fish Porridge', 
            title:"Fish Porridge (Lin Ji Yu Tang Yu Zhou 林記鱼汤鱼粥",
            image: require('../assets/WestFood/porriage.jpg'),
            text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
            rating: 3,
            status: 'All',
            category: 'breakfast',
            place: 'Boon Lay',
            subpage: 'Boon Lay Place Market and Food Village',
            subpageimg: require('../assets/WestHawker/BLM.jpg'),
            subpageadd: '221A Boon Lay Pl, Singapore 641221',
            subpagetime: '24 hours',
            subpagephone:62255632,
            subpagelat: 1.3467516321919029,
            subpagelong: 103.71298136931848,
            subpagemrt: 'Boon Lay',
            subpagebus: '180, 187, 240, 30, 99',
            subpageplace: 'Boon Lay',
            category: 'breakfast'
          },
          {
            key: 'Black Carrot Cake', 
            title:"Black Carrot Cake (Boon Lay Fried Carrot Cake & Kway Teow Mee)",
            image: require('../assets/WestFood/cake.jpg'),
            text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
            rating: 3,
            status: 'All',
            category: 'breakfast',
            place: 'Boon Lay',
            subpage: 'Boon Lay Place Market and Food Village',
            subpageimg: require('../assets/WestHawker/BLM.jpg'),
            subpageadd: '221A Boon Lay Pl, Singapore 641221',
            subpagetime: '24 hours',
            subpagephone:62255632,
            subpagelat: 1.3467516321919029,
            subpagelong: 103.71298136931848,
            subpagemrt: 'Boon Lay',
            subpagebus: '180, 187, 240, 30, 99',
            subpageplace: 'Boon Lay',
            category: 'breakfast'
          },
          {
            key: 'Boneless Duck Noodles', 
            title:"Boneless Duck Noodles (Heng Huat)",
            image: require('../assets/WestFood/duck.jpg'),
            text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
            rating: 3,
            status: 'All',
            category: 'breakfast',
            place: 'Boon Lay',
            subpage: 'Boon Lay Place Market and Food Village',
            subpageimg: require('../assets/WestHawker/BLM.jpg'),
            subpageadd: '221A Boon Lay Pl, Singapore 641221',
            subpagetime: '24 hours',
            subpagephone:62255632,
            subpagelat: 1.3467516321919029,
            subpagelong: 103.71298136931848,
            subpagemrt: 'Boon Lay',
            subpagebus: '180, 187, 240, 30, 99',
            subpageplace: 'Boon Lay',
            category: 'breakfast'
          },
          {
            key: 'Ming Kee Porriage', 
            title:'Ming Kee Porriage', 
            image: require('../assets/WestFood/congee.jpg'),
            text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
            rating: 3,
            status: 'All',
            category: 'breakfast',
            subpage: 'West Coast Market Square',
            subpageimg: require('../assets/WestHawker/726ClementiWS2.png'),
            subpageadd: '726 Clementi West Street 2, Singapore 120726',
            subpagephone:62255632,
            subpagelat: 1.305339125054957,
            subpagelong: 103.76449489643741,
            subpagemrt: 'Clementi',
            subpagebus: '143, 201, 30, 97',
            subpageplace: 'West Coast',
            category: 'breakfast',
            place: 'West Coast'
          },
          {
            key: 'Mee Siam (Hani Food Stall)', 
            title:'Mee Siam (Hani Food Stall)', 
            image: require('../assets/WestFood/mani.jpg'),
            text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
            rating: 3,
            status: 'All',
            category: 'breakfast',
            subpage: 'West Coast Market Square',
            subpageimg: require('../assets/WestHawker/726ClementiWS2.png'),
            subpageadd: '726 Clementi West Street 2, Singapore 120726',
            subpagephone:62255632,
            subpagelat: 1.305339125054957,
            subpagelong: 103.76449489643741,
            subpagemrt: 'Clementi',
            subpagebus: '143, 201, 30, 97',
            subpageplace: 'West Coast',
            category: 'breakfast',
            place: 'West Coast',
            status: 'Halal',
          },
          {
            key: '吉星 Hainanese Curry Rice', 
            title:'吉星 Hainanese Curry Rice', 
            image: require('../assets/WestFood/curry.jpg'),
            text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
            rating: 3,
            status: 'All',
            category: 'breakfast',
            subpage: 'West Coast Market Square',
            subpageimg: require('../assets/WestHawker/726ClementiWS2.png'),
            subpageadd: '726 Clementi West Street 2, Singapore 120726',
            subpagephone:62255632,
            subpagelat: 1.305339125054957,
            subpagelong: 103.76449489643741,
            subpagemrt: 'Clementi',
            subpagebus: '143, 201, 30, 97',
            subpageplace: 'West Coast',
            category: 'breakfast',
            place: 'West Coast'
          },
          {
            key: 'Mei Feng Roasted Chicken Rice', 
            title:'Mei Feng Roasted Chicken Rice', 
            image: require('../assets/WestFood/char.jpg'),
            text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
            rating: 3,
            status: 'All',
            category: 'breakfast',
            subpage: 'West Coast Market Square',
            subpageimg: require('../assets/WestHawker/726ClementiWS2.png'),
            subpageadd: '726 Clementi West Street 2, Singapore 120726',
            subpagephone:62255632,
            subpagelat: 1.305339125054957,
            subpagelong: 103.76449489643741,
            subpagemrt: 'Clementi',
            subpagebus: '143, 201, 30, 97',
            subpageplace: 'West Coast',
            category: 'breakfast',
            place: 'West Coast'
          },
          {
            key: 'Slice Fish, Fish Head, Seafood Soup', 
            title:'Slice Fish, Fish Head, Seafood Soup', 
            image: require('../assets/WestFood/fishnood.jpg'),
            text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
            rating: 3,
            status: 'All',
            category: 'breakfast',
            subpage: 'West Coast Market Square',
            subpageimg: require('../assets/WestHawker/726ClementiWS2.png'),
            subpageadd: '726 Clementi West Street 2, Singapore 120726',
            subpagephone:62255632,
            subpagelat: 1.305339125054957,
            subpagelong: 103.76449489643741,
            subpagemrt: 'Clementi',
            subpagebus: '143, 201, 30, 97',
            subpageplace: 'West Coast',
            category: 'breakfast',
            place: 'West Coast'
          },
          {
            key: 'Yong Tou Foo', 
            title:'Yong Tou Foo', 
            image: require('../assets/WestFood/ytf.jpg'),
            text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
            rating: 3,
            status: 'All',
            category: 'breakfast',
            subpage: 'West Coast Market Square',
            subpageimg: require('../assets/WestHawker/726ClementiWS2.png'),
            subpageadd: '726 Clementi West Street 2, Singapore 120726',
            subpagephone:62255632,
            subpagelat: 1.305339125054957,
            subpagelong: 103.76449489643741,
            subpagemrt: 'Clementi',
            subpagebus: '143, 201, 30, 97',
            subpageplace: 'West Coast',
            category: 'breakfast',
            place: 'West Coast'
          },
          {
            key: '合记 Braised Duck Rice Porridge Noodle', 
            title:'合记 Braised Duck Rice Porridge Noodle', 
            image: require('../assets/WestFood/braised.jpg'),
            text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
            rating: 3,
            status: 'All',
            category: 'breakfast',
            subpage: 'West Coast Market Square',
            subpageimg: require('../assets/WestHawker/726ClementiWS2.png'),
            subpageadd: '726 Clementi West Street 2, Singapore 120726',
            subpagephone:62255632,
            subpagelat: 1.305339125054957,
            subpagelong: 103.76449489643741,
            subpagemrt: 'Clementi',
            subpagebus: '143, 201, 30, 97',
            subpageplace: 'West Coast',
            category: 'breakfast',
            place: 'West Coast'
          }
          ];
