export 
    const dataList = [
      // breakfast
        {
          key: "Nasi Lemak (Boon Lay Power Nasi Lemak)", 
          title:"Nasi Lemak (Boon Lay Power Nasi Lemak)",
          image: require('../assets/WestFood/nasilemak.jpg'),
          text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled',
          video: 'KTK2lCyg0-k',
          rating: 4,
          status: 'Halal',
          place: 'Boon Lay',
          page: 'West',
          subpage: 'Boon Lay Place Market and Food Village',
          subpageimg: require('../assets/WestHawker/BLM.jpg'),
          subpageadd: '221A Boon Lay Pl, Singapore 641221',
          subpagetime: '24 hours',
          subpagephone:62255632,
          subpagelat: 1.3467516321919029,
          subpagelong: 103.71298136931848,
          subpagemrt: 'Boon Lay (EW27)',
          subpagebus: '180, 187, 240, 30, 99',
          subpageplace: 'Boon Lay',
          category: 'breakfast',
          store: require('../assets/WestFood/boonlaynasiStore.jpg'),
        }, 
        {
          key: 'Fried Kway Teow Mee (Ghee Huat)', 
          title:"Fried Kway Teow Mee (Ghee Huat)",
          image: require('../assets/WestFood/teow.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          place:'Boon Lay',
          subpage: 'Boon Lay Place Market and Food Village',
          subpageimg: require('../assets/WestHawker/BLM.jpg'),
          subpageadd: '221A Boon Lay Pl, Singapore 641221',
          subpagetime: '24 hours',
          subpagephone:62255632,
          subpagelat: 1.3467516321919029,
          subpagelong: 103.71298136931848,
          subpagemrt: 'Boon Lay (EW27)',
          subpagebus: '180, 187, 240, 30, 99',
          subpageplace: 'Boon Lay',
          category: 'breakfast'
        },   
        {
          key: 'Hokkien Prawn Mee (Ho Huat Fried Hokkien Prawn Mee)',
          title:"Hokkien Prawn Mee (Ho Huat Fried Hokkien Prawn Mee)",
          image: require('../assets/WestFood/hmee.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          category: 'breakfast',
          place: 'Boon Lay',
          subpage: 'Boon Lay Place Market and Food Village',
          subpageimg: require('../assets/WestHawker/BLM.jpg'),
          subpageadd: '221A Boon Lay Pl, Singapore 641221',
          subpagetime: '24 hours',
          subpagephone:62255632,
          subpagelat: 1.3467516321919029,
          subpagelong: 103.71298136931848,
          subpagemrt: 'Boon Lay (EW27)',
          subpagebus: '180, 187, 240, 30, 99',
          subpageplace: 'Boon Lay',
          category: 'breakfast'
        },
        {
          key: 'Ngoh Hiang (Xin Sheng Gor Hiong Prawn Cracker)', 
          title:"Ngoh Hiang (Xin Sheng Gor Hiong Prawn Cracker)",
          image: require('../assets/WestFood/ngoh.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          category: 'breakfast',
          place: 'Boon Lay',
          subpage: 'Boon Lay Place Market and Food Village',
          subpageimg: require('../assets/WestHawker/BLM.jpg'),
          subpageadd: '221A Boon Lay Pl, Singapore 641221',
          subpagetime: '24 hours',
          subpagephone:62255632,
          subpagelat: 1.3467516321919029,
          subpagelong: 103.71298136931848,
          subpagemrt: 'Boon Lay (EW27)',
          subpagebus: '180, 187, 240, 30, 99',
          subpageplace: 'Boon Lay',
          category: 'breakfast'
        }, 
        {
          key: 'Fish Porridge (Lin Ji Yu Tang Yu Zhou 林記鱼汤鱼粥', 
          title:"Fish Porridge (Lin Ji Yu Tang Yu Zhou 林記鱼汤鱼粥",
          image: require('../assets/WestFood/porriage.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          category: 'breakfast',
          subpage: 'Boon Lay Place Market and Food Village',
          subpageimg: require('../assets/WestHawker/BLM.jpg'),
          subpageadd: '221A Boon Lay Pl, Singapore 641221',
          subpagetime: '24 hours',
          subpagephone:62255632,
          subpagelat: 1.3467516321919029,
          subpagelong: 103.71298136931848,
          subpagemrt: 'Boon Lay (EW27)',
          subpagebus: '180, 187, 240, 30, 99',
          subpageplace: 'Boon Lay',
          category: 'breakfast'
        },
        {
          key: 'Black Carrot Cake (Boon Lay Fried Carrot Cake & Kway Teow Mee)', 
          title:"Black Carrot Cake (Boon Lay Fried Carrot Cake & Kway Teow Mee)",
          image: require('../assets/WestFood/cake.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          category: 'breakfast',
          subpage: 'Boon Lay Place Market and Food Village',
          subpageimg: require('../assets/WestHawker/BLM.jpg'),
          subpageadd: '221A Boon Lay Pl, Singapore 641221',
          subpagetime: '24 hours',
          subpagephone:62255632,
          subpagelat: 1.3467516321919029,
          subpagelong: 103.71298136931848,
          subpagemrt: 'Boon Lay (EW27)',
          subpagebus: '180, 187, 240, 30, 99',
          subpageplace: 'Boon Lay',
          category: 'breakfast'
        },
        {
          key: 'Boneless Duck Noodles (Heng Huat)', 
          title:"Boneless Duck Noodles (Heng Huat)",
          image: require('../assets/WestFood/duck.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          category: 'breakfast',
          subpage: 'Boon Lay Place Market and Food Village',
          subpageimg: require('../assets/WestHawker/BLM.jpg'),
          subpageadd: '221A Boon Lay Pl, Singapore 641221',
          subpagetime: '24 hours',
          subpagephone:62255632,
          subpagelat: 1.3467516321919029,
          subpagelong: 103.71298136931848,
          subpagemrt: 'Boon Lay (EW27)',
          subpagebus: '180, 187, 240, 30, 99',
          subpageplace: 'Boon Lay',
          category: 'breakfast'
        },
        {
          key: 'Ming Kee Porriage', 
          title:'Ming Kee Porriage', 
          image: require('../assets/WestFood/congee.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          category: 'breakfast',
          subpage: 'West Coast Market Square',
          subpageimg: require('../assets/WestHawker/726ClementiWS2.png'),
          subpageadd: '726 Clementi West Street 2, Singapore 120726',
          subpagephone:62255632,
          subpagelat: 1.305339125054957,
          subpagelong: 103.76449489643741,
          subpagemrt: 'Clementi MRT (EW23)',
          subpagebus: '143, 201, 30, 97',
          subpageplace: 'West Coast',
          category: 'breakfast',
          subpagetime: 'Daily 5.30am - 12am',
        },
        {
          key: 'Mee Siam (Hani Food Stall)', 
          title:'Mee Siam (Hani Food Stall)', 
          image: require('../assets/WestFood/mani.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          category: 'breakfast',
          subpage: 'West Coast Market Square',
          subpageimg: require('../assets/WestHawker/726ClementiWS2.png'),
          subpageadd: '726 Clementi West Street 2, Singapore 120726',
          subpagephone:62255632,
          subpagelat: 1.305339125054957,
          subpagelong: 103.76449489643741,
          subpagemrt: 'Clementi MRT (EW23)',
          subpagebus: '143, 201, 30, 97',
          subpageplace: 'West Coast',
          category: 'breakfast',
          subpagetime: 'Daily 5.30am - 12am',
        },
        {
          key: 'Mei Feng Roasted Chicken Rice', 
          title:'Mei Feng Roasted Chicken Rice', 
          image: require('../assets/WestFood/char.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          category: 'breakfast',
          subpage: 'West Coast Market Square',
          subpageimg: require('../assets/WestHawker/726ClementiWS2.png'),
          subpageadd: '726 Clementi West Street 2, Singapore 120726',
          subpagephone:62255632,
          subpagelat: 1.305339125054957,
          subpagelong: 103.76449489643741,
          subpagemrt: 'Clementi MRT (EW23)',
          subpagebus: '143, 201, 30, 97',
          subpageplace: 'West Coast',
          category: 'breakfast',
          place: 'West Coast',
          subpagetime: 'Daily 5.30am - 12am',
        },
        {
          key: 'Kok Kee Wanton Mee', 
          title:'Kok Kee Wanton Mee', 
          image: require('../assets/WestFood/wanto.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          subpage: 'Jurong West 505 Market & Food Centre',
          subpageimg: require('../assets/WestHawker/505JWS52.png'),
          subpageadd: '505 Jurong West Street 52, Singapore 640505',
          phone: 81268080,
          subpagelat: 1.3501442436603115,
          subpagelong: 103.71810659985844,
          subpagemrt: 'Lakeside MRT (EW26)',
          subpagebus: '657, NR5, 49, 5N, 99, 157, 185, 198, 334, 502',
          subpageplace: 'jw505',
          category: 'breakfast',
          place: 'jw505',
          subpagetime: 'Daily 6am - 9pm',
        },
        {
          key: 'Long Kee Wanton Noodles', 
          title:'Long Kee Wanton Noodles', 
          image: require('../assets/WestFood/lkwant.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          subpage: 'Jurong West 505 Market & Food Centre',
          subpageimg: require('../assets/WestHawker/505JWS52.png'),
          subpageadd: '505 Jurong West Street 52, Singapore 640505',
          phone: 81268080,
          subpagelat: 1.3501442436603115,
          subpagelong: 103.71810659985844,
          subpagemrt: 'Lakeside MRT (EW26)',
          subpagebus: '657, NR5, 49, 5N, 99, 157, 185, 198, 334, 502',
          subpageplace: 'jw505',
          category: 'breakfast',
          place: 'jw505',
          subpagetime: 'Daily 6am - 9pm',
        },
        {
          key: 'Bukit Timah Fried White Carrot Cake', 
          title:'Bukit Timah Fried White Carrot Cake', 
          image: require('../assets/WestFood/btcarrot.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          subpage: 'Jurong West 505 Market & Food Centre',
          subpageimg: require('../assets/WestHawker/505JWS52.png'),
          subpageadd: '505 Jurong West Street 52, Singapore 640505',
          phone: 81268080,
          subpagelat: 1.3501442436603115,
          subpagelong: 103.71810659985844,
          subpagemrt: 'Lakeside MRT (EW26)',
          subpagebus: '657, NR5, 49, 5N, 99, 157, 185, 198, 334, 502',
          subpageplace: 'jw505',
          category: 'breakfast',
          place: 'jw505',
          subpagetime: 'Daily 6am - 9pm',
        },
        {
          key: 'Soh Kee Cooked Food Porridge with Chicken Thigh', 
          title:'Soh Kee Cooked Food Porridge with Chicken Thigh', 
          image: require('../assets/WestFood/skcook.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          subpage: 'Jurong West 505 Market & Food Centre',
          subpageimg: require('../assets/WestHawker/505JWS52.png'),
          subpageadd: '505 Jurong West Street 52, Singapore 640505',
          phone: 81268080,
          subpagelat: 1.3501442436603115,
          subpagelong: 103.71810659985844,
          subpagemrt: 'Lakeside MRT (EW26)',
          subpagebus: '657, NR5, 49, 5N, 99, 157, 185, 198, 334, 502',
          subpageplace: 'jw505',
          category: 'breakfast',
          place: 'jw505',
          subpagetime: 'Daily 6am - 9pm',
        },
        {
          key: 'Na Bao Wan Fried Bee Hoon', 
          title:'Na Bao Wan Fried Bee Hoon', 
          image: require('../assets/WestFood/nabaowan.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          subpage: 'Jurong West 505 Market & Food Centre',
          subpageimg: require('../assets/WestHawker/505JWS52.png'),
          subpageadd: '505 Jurong West Street 52, Singapore 640505',
          phone: 81268080,
          subpagelat: 1.3501442436603115,
          subpagelong: 103.71810659985844,
          subpagemrt: 'Lakeside MRT (EW26)',
          subpagebus: '657, NR5, 49, 5N, 99, 157, 185, 198, 334, 502',
          subpageplace: 'jw505',
          category: 'breakfast',
          place: 'jw505',
          subpagetime: 'Daily 6am - 9pm',
        },
        {
          key: 'Wen Guang Handmade Fish Ball Noodle', 
          title:'Wen Guang Handmade Fish Ball Noodle', 
          image: require('../assets/WestFood/fishball.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          subpage: 'Jurong West 505 Market & Food Centre',
          subpageimg: require('../assets/WestHawker/505JWS52.png'),
          subpageadd: '505 Jurong West Street 52, Singapore 640505',
          phone: 81268080,
          subpagelat: 1.3501442436603115,
          subpagelong: 103.71810659985844,
          subpagemrt: 'Lakeside MRT (EW26)',
          subpagebus: '657, NR5, 49, 5N, 99, 157, 185, 198, 334, 502',
          subpageplace: 'jw505',
          category: 'breakfast',
          place: 'jw505',
          subpagetime: 'Daily 6am - 9pm',
        },
        {
          key: 'Traditional Hakka Lui Cha', 
          title:'Traditional Hakka Lui Cha', 
          image: require('../assets/WestFood/hakka.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          subpage: 'Jurong West 505 Market & Food Centre',
          subpageimg: require('../assets/WestHawker/505JWS52.png'),
          subpageadd: '505 Jurong West Street 52, Singapore 640505',
          phone: 81268080,
          subpagelat: 1.3501442436603115,
          subpagelong: 103.71810659985844,
          subpagemrt: 'Lakeside MRT (EW26)',
          subpagebus: '657, NR5, 49, 5N, 99, 157, 185, 198, 334, 502',
          subpageplace: 'jw505',
          category: 'breakfast',
          place: 'jw505',
          subpagetime: 'Daily 6am - 9pm',
        },
        {
          key: 'Heng Heng Cooked Food Slice Fish Soup', 
          title:'Heng Heng Cooked Food Slice Fish Soup', 
          image: require('../assets/WestFood/hengheng.jpg'),
          text:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
          rating: 3,
          status: 'All',
          subpage: 'Jurong West 505 Market & Food Centre',
          subpageimg: require('../assets/WestHawker/505JWS52.png'),
          subpageadd: '505 Jurong West Street 52, Singapore 640505',
          phone: 81268080,
          subpagelat: 1.3501442436603115,
          subpagelong: 103.71810659985844,
          subpagemrt: 'Lakeside MRT (EW26)',
          subpagebus: '657, NR5, 49, 5N, 99, 157, 185, 198, 334, 502',
          subpageplace: 'jw505',
          category: 'breakfast',
          place: 'jw505',
          subpagetime: 'Daily 6am - 9pm',
        }
          ];
